### ISSUE TITLE
Use readxl instead of XLConnect

### ISSUE THREAD

**Issue by andrewdolman** [dkneis/rodeoApp#1]
Just a suggestion. 

You could use readxl, http://cran.r-project.org/web/packages/readxl/index.html, instead of XLConnect, to remove the dependency on Java. It is cross-platform. 

Alternatively, can XLConnect go in the Suggests: category?

**Comment by dkneis** [comment]
Done. The latest version of rodeoApp now uses package 'readxl' instead of 'XLConnect'. Thanks Andrew.
